import type { DesignerWithProjects } from '@/types'

export const MOCK_DESIGNERS: DesignerWithProjects[] = [
  {
    id: '1',
    slug: 'camille-lefebvre',
    firstName: 'Camille',
    lastName: 'Lefebvre',
    email: 'camille@example.com',
    photoUrl: null,
    bio: 'Designer graphique passionnée par la typographie et l\'identité visuelle. Après 8 ans d\'expérience en agence parisienne, je me suis installée à Rouen pour accompagner les acteurs normands dans leur communication visuelle. Mon approche allie rigueur suisse et sensibilité locale.',
    city: 'Rouen',
    territory: 'SEINE_MARITIME',
    disciplines: ['DESIGN_GRAPHIQUE', 'DESIGN_TYPOGRAPHIQUE'],
    specialties: ['Identité visuelle', 'Édition', 'Typographie'],
    structure: 'FREELANCE',
    seniority: 'SENIOR',
    transitionFocuses: ['ECOLOGIQUE', 'NUMERIQUE_RESPONSABLE'],
    isOpenToCollaboration: true,
    website: 'https://camillelefebvre.fr',
    linkedin: 'https://linkedin.com/in/camillelefebvre',
    instagram: 'https://instagram.com/camille.design',
    behance: null,
    status: 'APPROVED',
    createdAt: new Date('2024-01-15'),
    updatedAt: new Date('2024-06-01'),
    projects: [
      {
        id: 'p1',
        title: 'Identité visuelle — Fromagerie Normande',
        slug: 'identite-fromagerie-normande',
        description:
          'Refonte complète de l\'identité visuelle d\'une fromagerie artisanale du Pays de Caux. Logotype, packaging et signalétique.',
        imageUrl: null,
        year: 2024,
        designerId: '1',
        createdAt: new Date('2024-03-10'),
      },
      {
        id: 'p2',
        title: 'Affiche — Festival Terres de Paroles',
        slug: 'affiche-terres-de-paroles',
        description:
          'Conception de l\'affiche officielle du festival littéraire Terres de Paroles, édition 2024.',
        imageUrl: null,
        year: 2024,
        designerId: '1',
        createdAt: new Date('2024-05-20'),
      },
    ],
  },
  {
    id: '2',
    slug: 'thomas-morel',
    firstName: 'Thomas',
    lastName: 'Morel',
    email: 'thomas@example.com',
    photoUrl: null,
    bio: 'Designer produit spécialisé dans le mobilier durable et l\'éco-conception. Mon atelier au Havre me permet de travailler en lien étroit avec les artisans locaux et les matériaux biosourcés de la région.',
    city: 'Le Havre',
    territory: 'SEINE_MARITIME',
    disciplines: ['DESIGN_PRODUIT', 'DESIGN_INDUSTRIEL'],
    specialties: ['Mobilier', 'Éco-conception', 'Prototypage'],
    structure: 'FREELANCE',
    seniority: 'CONFIRME',
    transitionFocuses: ['ECOLOGIQUE', 'ECONOMIE_CIRCULAIRE'],
    isOpenToCollaboration: true,
    website: 'https://thomasmorel.design',
    linkedin: null,
    instagram: 'https://instagram.com/thomas.morel.design',
    behance: 'https://behance.net/thomasmorel',
    status: 'APPROVED',
    createdAt: new Date('2024-02-20'),
    updatedAt: new Date('2024-05-15'),
    projects: [
      {
        id: 'p3',
        title: 'Chaise — Collection Estuaire',
        slug: 'chaise-collection-estuaire',
        description:
          'Chaise en bois de hêtre normand, inspirée des formes de l\'estuaire de la Seine.',
        imageUrl: null,
        year: 2023,
        designerId: '2',
        createdAt: new Date('2024-01-05'),
      },
    ],
  },
  {
    id: '3',
    slug: 'manon-dubois',
    firstName: 'Manon',
    lastName: 'Dubois',
    email: 'manon@example.com',
    photoUrl: null,
    bio: 'Designer de service et facilitatrice, j\'accompagne les collectivités et associations normandes dans leurs démarches d\'innovation sociale. Convaincue que le design peut transformer les politiques publiques.',
    city: 'Caen',
    territory: 'CALVADOS',
    disciplines: ['DESIGN_SERVICE', 'DESIGN_SOCIAL'],
    specialties: ['Design de politiques publiques', 'Facilitation', 'Co-conception'],
    structure: 'AGENCE',
    seniority: 'CONFIRME',
    transitionFocuses: ['SOCIALE', 'INCLUSION'],
    isOpenToCollaboration: false,
    website: null,
    linkedin: 'https://linkedin.com/in/manondubois',
    instagram: null,
    behance: null,
    status: 'APPROVED',
    createdAt: new Date('2024-03-05'),
    updatedAt: new Date('2024-04-22'),
    projects: [],
  },
  {
    id: '4',
    slug: 'lucas-renard',
    firstName: 'Lucas',
    lastName: 'Renard',
    email: 'lucas@example.com',
    photoUrl: null,
    bio: 'Motion designer et illustrateur basé à Évreux. Je crée des animations et des illustrations pour le web, la publicité et l\'événementiel. Fan de narration visuelle et d\'expérimentations graphiques.',
    city: 'Évreux',
    territory: 'EURE',
    disciplines: ['MOTION_DESIGN', 'ILLUSTRATION'],
    specialties: ['Animation 2D', 'Illustration éditoriale', 'Storyboard'],
    structure: 'FREELANCE',
    seniority: 'JUNIOR',
    transitionFocuses: [],
    isOpenToCollaboration: true,
    website: 'https://lucasrenard.com',
    linkedin: null,
    instagram: 'https://instagram.com/lucas.renard',
    behance: 'https://behance.net/lucasrenard',
    status: 'APPROVED',
    createdAt: new Date('2024-04-10'),
    updatedAt: new Date('2024-06-08'),
    projects: [
      {
        id: 'p4',
        title: 'Clip animé — Orchestre de Normandie',
        slug: 'clip-orchestre-normandie',
        description:
          'Réalisation d\'un clip d\'animation 2D pour promouvoir la saison culturelle de l\'orchestre régional.',
        imageUrl: null,
        year: 2024,
        designerId: '4',
        createdAt: new Date('2024-04-20'),
      },
      {
        id: 'p5',
        title: 'Illustrations — Guide touristique de l\'Eure',
        slug: 'illustrations-guide-eure',
        description:
          'Série d\'illustrations pour le guide touristique du département de l\'Eure, mettant en valeur le patrimoine local.',
        imageUrl: null,
        year: 2023,
        designerId: '4',
        createdAt: new Date('2023-11-15'),
      },
    ],
  },
  {
    id: '5',
    slug: 'elise-martin',
    firstName: 'Élise',
    lastName: 'Martin',
    email: 'elise@example.com',
    photoUrl: null,
    bio: 'UX/UI designer avec une approche centrée sur l\'accessibilité et le numérique responsable. Salariée dans une ESN caennaise, je conçois des interfaces inclusives pour des clients publics et privés.',
    city: 'Caen',
    territory: 'CALVADOS',
    disciplines: ['DESIGN_NUMERIQUE', 'DESIGN_EXPERIENCE'],
    specialties: ['UX Research', 'Accessibilité', 'Design system'],
    structure: 'SALARIE',
    seniority: 'CONFIRME',
    transitionFocuses: ['NUMERIQUE_RESPONSABLE', 'INCLUSION'],
    isOpenToCollaboration: false,
    website: 'https://elise-martin.fr',
    linkedin: 'https://linkedin.com/in/elisemartin',
    instagram: null,
    behance: null,
    status: 'APPROVED',
    createdAt: new Date('2024-01-28'),
    updatedAt: new Date('2024-05-30'),
    projects: [
      {
        id: 'p6',
        title: 'Refonte UX — Portail citoyen de Caen',
        slug: 'refonte-portail-caen',
        description:
          'Refonte de l\'expérience utilisateur du portail citoyen de la ville de Caen, avec un focus sur l\'accessibilité RGAA.',
        imageUrl: null,
        year: 2024,
        designerId: '5',
        createdAt: new Date('2024-02-10'),
      },
    ],
  },
  {
    id: '6',
    slug: 'antoine-leclerc',
    firstName: 'Antoine',
    lastName: 'Leclerc',
    email: 'antoine@example.com',
    photoUrl: null,
    bio: 'Designer d\'espace et scénographe. Je conçois des lieux de vie, des espaces d\'exposition et des aménagements urbains à Alençon et dans toute la Normandie. Passionné par le patrimoine et sa réinterprétation contemporaine.',
    city: 'Alençon',
    territory: 'ORNE',
    disciplines: ['DESIGN_ESPACE', 'DESIGN_STRATEGIQUE'],
    specialties: ['Scénographie', 'Aménagement intérieur', 'Urbanisme'],
    structure: 'AGENCE',
    seniority: 'EXPERT',
    transitionFocuses: ['ECOLOGIQUE', 'MOBILITE'],
    isOpenToCollaboration: true,
    website: 'https://atelierleclerc.fr',
    linkedin: 'https://linkedin.com/in/antoineleclerc',
    instagram: 'https://instagram.com/atelier.leclerc',
    behance: null,
    status: 'APPROVED',
    createdAt: new Date('2024-02-05'),
    updatedAt: new Date('2024-06-12'),
    projects: [
      {
        id: 'p7',
        title: 'Scénographie — Musée des Beaux-Arts d\'Alençon',
        slug: 'scenographie-musee-alencon',
        description:
          'Conception de la scénographie de l\'exposition temporaire « Dentelle & Design » au musée des Beaux-Arts d\'Alençon.',
        imageUrl: null,
        year: 2024,
        designerId: '6',
        createdAt: new Date('2024-05-01'),
      },
      {
        id: 'p8',
        title: 'Aménagement — Tiers-lieu Le Fablab Ornais',
        slug: 'amenagement-fablab-ornais',
        description:
          'Aménagement intérieur d\'un tiers-lieu dédié à la fabrication numérique et aux rencontres créatives.',
        imageUrl: null,
        year: 2023,
        designerId: '6',
        createdAt: new Date('2023-09-20'),
      },
    ],
  },
]
